name: API Pytest

on:
    pull_request:
        branches: '**'

jobs:
    Pytest:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v2
              with:
                  python-version: '3.11.6'
            - name: Install packages
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
                  pip install pytest
            - name: Start SQL server
              run: |
                  sudo apt-get install mysql-server
                  mysql -h ${{secrets.DB_HOSTNAME}} -u ${{secrets.DB_USERNAME}} -p${{secrets.DB_PASSWORD}} 
                  sleep 10
            - name: Run API Tests
              run: |
                  python -m flask run & python -m pytest test_api.py
