name: API Pytest

on:
    pull_request:
        branches: '**'

jobs:
    Pytest:
        runs-on: ubuntu-latest
        env:
            DB_HOST: localhost
            DB_USER: root
            DB_PASSWORD: password123
            DB_NAME: usersdb
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v2
              with:
                  python-version: '3.11.6'
            - name: Install packages
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
                  pip install pytest
            - name: Start SQL server
              run: |
                  mysql -h $DB_HOST -u $DB_USER -p$DB_PASSWORD -e "USE $DB_NAME 
                  sleep 10
            - name: Run API Tests
            - run: |
                  python -m flask run & python -m pytest test_api.py
