name: UI Pytest

on:
    pull_request:
        branches: '**'

jobs:
    Pytest:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v2
              with:
                  python-version: '3.11.6'
            - name: Install packages
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
                  pip install pytest
                  pip install pytest-playwright
                  playwright install
                  npm install -g npm
                  npm install -g @angular/cli
                  npm install
            - name: Start MYSQL server
              run: |
                  mysql -h ${{secrets.DB_HOSTNAME}} -u ${{secrets.DB_USERNAME}} -p${{secrets.DB_PASSWORD}}
                  sleep 10
            - name: Run Ui Tests
              run: |
                  ng serve & python -m pytest test_ui.py & python -m flask run
