name: UI Pytest

on:
    pull_request:
        branches: '**'

jobs:
    Pytest:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v2
              with:
                  python-version: '3.11.6'
            - name: Install packages
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
                  pip install pytest
                  pip install pytest-playwright
                  playwright install
                  npm install -g npm
                  npm install -g @angular/cli
                  npm install
            - name: Start SQL server and Run tests
              run: |
                  sudo apt install mysql-server
                  sudo service mysql start
                  sleep 10
                  ng serve & python -m pytest test_ui.py & python -m flask run
